version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/mojis/
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 3600
     runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 3600
     runas: root
