version: "3.9"

services:
    web:
        container_name: web
        restart: always
        build:
          context: .
          dockerfile: ./nginx/Dockerfile
          args:
              ENV: ${ENV}
        env_file:
            - .env
        ports:
          - 80:80
          - 443:443
        depends_on:
          - backend
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
          - ./tmp/etc/letsencrypt:/etc/letsencrypt
          - ./tmp/certbot/data:/var/www/certbot
    certbot:
        container_name: certbot
        image: certbot/certbot:latest
        depends_on:
          - web
        command: >-
                certonly --reinstall --webroot --webroot-path=/var/www/certbot
                --email ${EMAIL} --agree-tos --no-eff-email
                -d ${DOMAIN} --dry-run
        volumes:
          - ./tmp/etc/letsencrypt:/etc/letsencrypt
          - ./tmp/certbot/data:/var/www/certbot
    backend:
        container_name: backend
        restart: always
        build: backend
        environment:
          - PORT=8000
        ports:
          - 8000:8000
        environment:
          - HOST=${HOST}
          - SECRET_KEY=${SECRET_KEY}
          - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
          - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
          - MONGO_URL=${MONGO_URL}
        extra_hosts:
          - "host.docker.internal:host-gateway"
