version: "3.9"

services:
    web:
        restart: always
        build:
          context: nginx
          args:
              ENV: ${ENV}
        env_file:
            - .env
        ports:
          - 80:80
          - 443:443
        depends_on:
          - backend
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
          - "./nginx/certs:/etc/nginx/certs"
    backend:
        restart: always
        build: backend
        environment:
          - PORT=8000
        ports:
          - 8000:8000
        depends_on:
          - db
        environment:
          - HOST=${HOST}
          - SECRET_KEY=${SECRET_KEY}
          - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
          - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    db:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - MONGO_INITDB_DATABASE=gellies
