version: "3.9"

services:
    web:
        restart: always
        build: nginx
        ports:
          - 80:80
          - 443:443
        depends_on:
          - backend
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
          - ./data/certbot/conf:/etc/letsencrypt:ro
    backend:
        restart: always
        build: backend
        environment:
          - PORT=8000
        ports:
          - 8000:8000
        depends_on:
          - db
    db:
      image: mongo
      restart: always
      ports:
        - 27017:27017
