version: "3.9"

services:
    web:
        restart: always
        build: .
        ports:
          - 80:80
        depends_on:
          - backend
    backend:
        restart: always
        build: backend
        environment:
          - PORT=8000
        ports:
          - 8000:8000
